version: "3.8"

services:
  web:
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"
    container_name: todo-web
    volumes:
      - .:/code
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: todo-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  keycloak_data:
