"""unique_username

Revision ID: 524bb969a023
Revises: a433fdf54984
Create Date: 2023-02-25 13:43:50.486695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '524bb969a023'
down_revision = 'a433fdf54984'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
