"""add_status_in_task

Revision ID: e5339b71e963
Revises: 13fe048db790
Create Date: 2023-02-25 15:24:22.730265

"""
import sqlalchemy_utils
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5339b71e963'
down_revision = '13fe048db790'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    statuses = [('open', 'open'), ('done', 'done')]

    op.add_column('tasks', sa.Column('status', sqlalchemy_utils.types.choice.ChoiceType(statuses), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'status')
    # ### end Alembic commands ###
